// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_bNXcX_1C2BL7HIvxn6kDp43B-j_lGA',
    appId: '1:592044899006:web:f9e5a1faf7df0b7da37cef',
    messagingSenderId: '592044899006',
    projectId: 'latihan-1-6427c',
    authDomain: 'latihan-1-6427c.firebaseapp.com',
    storageBucket: 'latihan-1-6427c.firebasestorage.app',
    measurementId: 'G-GH34XVJJSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ3UCof_nnwe5DzaXGig_UDaTWx_oCL7s',
    appId: '1:592044899006:android:68edc93375f4d7c8a37cef',
    messagingSenderId: '592044899006',
    projectId: 'latihan-1-6427c',
    storageBucket: 'latihan-1-6427c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVwJKaQHtEuFG8xziaJiNkKTZwsoqk9k',
    appId: '1:592044899006:ios:de805ebd83eb313da37cef',
    messagingSenderId: '592044899006',
    projectId: 'latihan-1-6427c',
    storageBucket: 'latihan-1-6427c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingTangerang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIVwJKaQHtEuFG8xziaJiNkKTZwsoqk9k',
    appId: '1:592044899006:ios:de805ebd83eb313da37cef',
    messagingSenderId: '592044899006',
    projectId: 'latihan-1-6427c',
    storageBucket: 'latihan-1-6427c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingTangerang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_bNXcX_1C2BL7HIvxn6kDp43B-j_lGA',
    appId: '1:592044899006:web:8c3b0ec93c30762ca37cef',
    messagingSenderId: '592044899006',
    projectId: 'latihan-1-6427c',
    authDomain: 'latihan-1-6427c.firebaseapp.com',
    storageBucket: 'latihan-1-6427c.firebasestorage.app',
    measurementId: 'G-6ZXEBTHH2K',
  );
}
